import json
import os

def load_db():
    if os.path.exists('modules.json'):
        with open('modules.json', 'r', encoding='utf-8') as f:
            return json.load(f)
    return []

def save_db(db):
    with open('modules.json', 'w', encoding='utf-8') as f:
        json.dump(db, f, indent=2, ensure_ascii=False)

def main():
    db = load_db()
    
    # Core Java structure
    core_java = {
        "id": 0,
        "name": "Core Java",
        "short": "Core Java",
        "color": "c-purple",
        "count": 55,
        "subs": [
            {
                "head": "JVM & Basics",
                "qs": [
                    {
                        "q": "What is the difference between JDK, JRE, and JVM?",
                        "a": "<h4>Definitions & Key Differences</h4><ul>"
                            "<li><strong>JVM (Java Virtual Machine):</strong> The core engine that executes Java bytecode. It is platform-dependent and provides the runtime environment for Java execution.</li>"
                            "<li><strong>JRE (Java Runtime Environment):</strong> The bundle containing the JVM plus core runtime libraries/classes required to run Java applications. It is for running, not developing.</li>"
                            "<li><strong>JDK (Java Development Kit):</strong> The full software development kit containing the JRE plus development tools (javac, debugger, javadoc, jar). It is used to write and compile Java code.</li>"
                            "</ul><pre>JDK = JRE + Development Tools\nJRE = JVM + Core Class Libraries</pre>"
                    },
                    {
                        "q": "Explain the JVM architecture — class loader, runtime data areas, execution engine.",
                        "a": "<h4>JVM Architecture Components</h4>"
                            "1. <strong>Class Loader Subsystem:</strong> Responsible for Loading, Linking, and Initializing class files. It uses delegation models (Bootstrap, Extension, Application classloaders).<br/>"
                            "2. <strong>Runtime Data Areas (Memory):</strong>"
                            "<ul>"
                            "<li><strong>Method Area:</strong> Stores class-level data, constant pool, method metadata, static variables.</li>"
                            "<li><strong>Heap Area:</strong> Stores all objects and instance variables. Shared across threads.</li>"
                            "<li><strong>Stack Area:</strong> Stores local variables, frame data, and method calls. Separate stack per thread.</li>"
                            "<li><strong>PC Registers:</strong> Stores the address of the current execution instruction for each thread.</li>"
                            "<li><strong>Native Method Stack:</strong> Stores native method information.</li>"
                            "</ul>"
                            "3. <strong>Execution Engine:</strong> Executes the bytecode using the Interpreter, JIT Compiler (Just-In-Time to compile hot spots to machine code), and Garbage Collector."
                    },
                    {
                        "q": "What happens when you run a Java program (compilation to execution)?",
                        "a": "<h4>Step-by-Step Flow</h4>"
                            "<ol>"
                            "<li><strong>Write Code:</strong> Developer writes source code in <code>.java</code> files.</li>"
                            "<li><strong>Compilation:</strong> The Java Compiler (<code>javac</code>) compiles source code into <code>.class</code> files containing bytecode.</li>"
                            "<li><strong>Loading:</strong> The JVM Class Loader loads the <code>.class</code> file into memory.</li>"
                            "<li><strong>Verification:</strong> Bytecode Verifier ensures the code conforms to security rules.</li>"
                            "<li><strong>Execution:</strong> The Interpreter executes instructions line-by-line. The JIT Compiler compiles highly executed sections into native machine code for direct execution.</li>"
                            "</ol>"
                    },
                    {
                        "q": "What is bytecode? Why is Java platform-independent?",
                        "a": "<h4>Bytecode & Platform Independence</h4>"
                            "<ul>"
                            "<li><strong>Bytecode:</strong> An intermediate, highly optimized instruction set generated by compilation. It is not native to any processor but is native to the JVM.</li>"
                            "<li><strong>Independence:</strong> Java compiler creates bytecode (<code>.class</code>) which runs on any system having a platform-specific JRE (JVM). Hence the motto: <em>Write Once, Run Anywhere (WORA)</em>.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between stack memory and heap memory?",
                        "a": "<h4>Stack vs. Heap Memory</h4>"
                            "<table>"
                            "<tr><th>Feature</th><th>Stack Memory</th><th>Heap Memory</th></tr>"
                            "<tr><td><strong>Storage</strong></td><td>Local variables, primitive types, reference pointers</td><td>All created objects and instance variables</td></tr>"
                            "<tr><td><strong>Access</strong></td><td>LIFO (Last-In-First-Out), very fast</td><td>Random access, slower due to complex lookup</td></tr>"
                            "<tr><td><strong>Size</strong></td><td>Fixed size, relatively small</td><td>Dynamic size, much larger</td></tr>"
                            "<tr><td><strong>Lifespan</strong></td><td>Exists while current method frame is alive</td><td>Exists as long as referenced, cleaned by GC</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is garbage collection? Explain how it works.",
                        "a": "<h4>Garbage Collection (GC)</h4>"
                            "Automatic memory management that reclaims heap memory by destroying unreachable objects.<br/>"
                            "<h4>How it works:</h4>"
                            "1. <strong>Marking:</strong> GC identifies which objects are in-use and which are dereferenced.<br/>"
                            "2. <strong>Sweeping:</strong> GC removes dead objects.<br/>"
                            "3. <strong>Compacting:</strong> Moves remaining live objects together to reduce fragmentation.<br/>"
                            "<h4>Generational Heap Structure:</h4>"
                            "<ul>"
                            "<li><strong>Young Generation:</strong> Where new objects are allocated (Eden space, Survivor spaces S0, S1). Minor GC runs here frequently.</li>"
                            "<li><strong>Old (Tenured) Generation:</strong> Holds long-surviving objects. Major GC runs here.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the finalize() method? Why is it deprecated?",
                        "a": "<h4>finalize() Method</h4>"
                            "Historically invoked by JVM before garbage collecting an object to release resources.<br/>"
                            "<h4>Why Deprecated:</h4>"
                            "<ul>"
                            "<li>Unpredictable execution timing (no guarantee when or if it will run).</li>"
                            "<li>Performance overhead.</li>"
                            "<li>Can cause object resurrection (making object reachable again during finalize).</li>"
                            "</ul>"
                            "<em>Alternative:</em> Use <code>try-with-resources</code> and implement <code>AutoCloseable</code>."
                    }
                ]
            },
            {
                "head": "OOP Concepts",
                "qs": [
                    {
                        "q": "What are the four pillars of OOP? Explain each.",
                        "a": "<h4>The Four Pillars of OOP</h4>"
                            "1. <strong>Encapsulation:</strong> Bundling data (variables) and methods together, protecting data from unauthorized access using private modifiers and public getter/setter methods.<br/>"
                            "2. <strong>Inheritance:</strong> Mechanism where one class acquires the properties and behaviors of a parent class (using <code>extends</code> or <code>implements</code>). Promotes code reusability.<br/>"
                            "3. <strong>Polymorphism:</strong> The ability of a message or method to be displayed/behave in more than one form (compile-time overloading, runtime overriding).<br/>"
                            "4. <strong>Abstraction:</strong> Hiding internal details and showing only essential features to the user (using abstract classes and interfaces)."
                    },
                    {
                        "q": "What is the difference between method overloading and method overriding?",
                        "a": "<h4>Overloading vs. Overriding</h4>"
                            "<table>"
                            "<tr><th>Feature</th><th>Method Overloading</th><th>Method Overriding</th></tr>"
                            "<tr><td><strong>Concept</strong></td><td>Compile-time polymorphism</td><td>Runtime polymorphism</td></tr>"
                            "<tr><td><strong>Class</strong></td><td>Occurs within the same class</td><td>Occurs between Parent & Child classes</td></tr>"
                            "<tr><td><strong>Signature</strong></td><td>Must have different parameter lists</td><td>Must have the exact same signature</td></tr>"
                            "<tr><td><strong>Return Type</strong></td><td>Can be different</td><td>Must be same or covariant</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is runtime polymorphism? Give a code example.",
                        "a": "<h4>Runtime Polymorphism</h4>"
                            "A process in which a call to an overridden method is resolved at runtime rather than compile-time based on the object instance.<br/>"
                            "<pre>class Animal {\n  void sound() { System.out.println(\"Animal sound\"); }\n}\n"
                            "class Dog extends Animal {\n  void sound() { System.out.println(\"Bark\"); }\n}\n"
                            "// Usage:\nAnimal a = new Dog();\na.sound(); // Output: Bark (dynamic binding)</pre>"
                    },
                    {
                        "q": "What is the difference between an abstract class and an interface?",
                        "a": "<h4>Abstract Class vs. Interface (Java 8+)</h4>"
                            "<table>"
                            "<tr><th>Abstract Class</th><th>Interface</th></tr>"
                            "<tr><td>Can have instance variables (state).</td><td>Can only have static final variables (constants).</td></tr>"
                            "<tr><td>Can have constructor.</td><td>Cannot have constructors.</td></tr>"
                            "<tr><td>Single inheritance (extends only one).</td><td>Multiple inheritance (implements multiple).</td></tr>"
                            "<tr><td>Can have any access modifiers on methods.</td><td>Methods are implicitly public.</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "Can an interface have a constructor? Why or why not?",
                        "a": "<h4>Interface Constructors</h4>"
                            "<strong>No</strong>, interfaces cannot have constructors. Why?<br/>"
                            "<ul>"
                            "<li>Interfaces are meant to be pure contracts specifying behavior, not maintaining state.</li>"
                            "<li>They cannot be instantiated directly, and they cannot have instance variables to initialize.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What are default and static methods in interfaces (Java 8+)?",
                        "a": "<h4>Default & Static Methods</h4>"
                            "Introduced in Java 8 to allow adding new methods to interfaces without breaking existing implementations.<br/>"
                            "<ul>"
                            "<li><strong>Default Methods (<code>default</code>):</strong> Have a method body and can be overridden by classes implementing the interface.</li>"
                            "<li><strong>Static Methods (<code>static</code>):</strong> Have a method body but belong to the interface class itself, cannot be overridden, and are called using the interface name.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is covariant return type in overriding?",
                        "a": "<h4>Covariant Return Type</h4>"
                            "Refers to a child class method overriding a parent method and returning a more specific (subclass) type than the parent method's return type.<br/>"
                            "<pre>class Parent {\n  Parent get() { return this; }\n}\n"
                            "class Child extends Parent {\n  @Override\n  Child get() { return this; } // Legal in Java 5+\n}</pre>"
                    },
                    {
                        "q": "What is the difference between this and super keywords?",
                        "a": "<h4>this vs. super</h4>"
                            "<ul>"
                            "<li><strong><code>this</code>:</strong> Points to the current instance of the class. Used to access current class constructors, methods, and fields.</li>"
                            "<li><strong><code>super</code>:</strong> Points to the immediate parent class instance. Used to access parent class constructors, methods, and overridden fields.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is constructor chaining using this() and super()?",
                        "a": "<h4>Constructor Chaining</h4>"
                            "Calling one constructor from another constructor within the same class (using <code>this()</code>) or from the parent class (using <code>super()</code>).<br/>"
                            "<strong>Rules:</strong><br/>"
                            "1. <code>this()</code> or <code>super()</code> must be the absolute first statement in the constructor.<br/>"
                            "2. You cannot use both in the same constructor."
                    },
                    {
                        "q": "What a marker interface? Give two examples.",
                        "a": "<h4>Marker Interface</h4>"
                            "An empty interface (no fields or methods) used to deliver metadata or 'mark' a class for special treatment by the compiler or JVM.<br/>"
                            "<h4>Examples:</h4>"
                            "<ul>"
                            "<li><code>java.io.Serializable</code>: Marks class objects as serializable.</li>"
                            "<li><code>java.lang.Cloneable</code>: Authorizes the use of <code>Object.clone()</code>.</li>"
                            "</ul>"
                    }
                ]
            },
            {
                "head": "Strings",
                "qs": [
                    {
                        "q": "Why is String immutable in Java?",
                        "a": "<h4>Reasons for String Immutability</h4>"
                            "1. <strong>String Pool Cache:</strong> Enables reusing string literals, reducing memory usage.<br/>"
                            "2. <strong>Security:</strong> Strings are used for database credentials, file paths, and network connections. Mutation could compromise these resources.<br/>"
                            "3. <strong>Thread Safety:</strong> Multiple threads can share strings without synchronization synchronization bugs.<br/>"
                            "4. <strong>HashCode Caching:</strong> The hashcode of a String is cached upon creation, making hashmap operations fast."
                    },
                    {
                        "q": "What is the String pool (intern pool)? How does it work?",
                        "a": "<h4>String Pool</h4>"
                            "A special storage area in Java heap memory where string literals are cached.<br/>"
                            "<ul>"
                            "<li>When you write <code>String s = \"hello\";</code>, JVM looks for \"hello\" in the pool. If found, it returns the reference. If not, it creates a new string in the pool.</li>"
                            "<li>Using <code>new String(\"hello\")</code> bypasses the pool and allocates a new object in the general heap space.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between String, StringBuilder, and StringBuffer?",
                        "a": "<h4>String comparison</h4>"
                            "<table>"
                            "<tr><th>Feature</th><th>String</th><th>StringBuilder</th><th>StringBuffer</th></tr>"
                            "<tr><td><strong>Mutability</strong></td><td>Immutable</td><td>Mutable</td><td>Mutable</td></tr>"
                            "<tr><td><strong>Thread-Safe</strong></td><td>Yes</td><td>No</td><td>Yes (synchronized)</td></tr>"
                            "<tr><td><strong>Performance</strong></td><td>Slower on updates</td><td>Fastest</td><td>Slower than Builder</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is the difference between == and .equals() for Strings?",
                        "a": "<h4>== vs. equals()</h4>"
                            "<ul>"
                            "<li><strong><code>==</code>:</strong> Compares memory references (checks if both pointers point to the exact same object location).</li>"
                            "<li><strong><code>.equals()</code>:</strong> Compares the actual sequence of characters inside the String (value equivalence).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What does String.intern() do?",
                        "a": "<h4>String.intern()</h4>"
                            "Explicitly puts a string object in the String pool or returns its reference if it already exists.<br/>"
                            "<pre>String s1 = new String(\"test\");\nString s2 = s1.intern(); // s2 points to pool\n"
                            "String s3 = \"test\";\nSystem.out.println(s2 == s3); // Output: true</pre>"
                    }
                ]
            },
            {
                "head": "Keywords & Modifiers",
                "qs": [
                    {
                        "q": "What is the difference between final, finally, and finalize?",
                        "a": "<h4>final vs. finally vs. finalize</h4>"
                            "<ul>"
                            "<li><strong><code>final</code>:</strong> Modifier keyword. A final class cannot be inherited, a final method cannot be overridden, and a final variable cannot be reassigned.</li>"
                            "<li><strong><code>finally</code>:</strong> Block used in exception handling. Guaranteed to execute after try-catch to perform resource cleanup.</li>"
                            "<li><strong><code>finalize()</code>:</strong> Clean-up method invoked by garbage collector before object destruction.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What does the static keyword mean? Can static methods be overridden?",
                        "a": "<h4>static Keyword</h4>"
                            "Belongs to the class blueprint rather than any specific object instance.<br/>"
                            "<strong>Can static methods be overridden?</strong> No. Method overriding is dynamic dispatch resolved at runtime. Static methods are resolved statically at compile-time (Method Hiding)."
                    },
                    {
                        "q": "What is the volatile keyword?",
                        "a": "<h4>volatile Keyword</h4>"
                            "Ensures that changes to a variable are always written directly to main memory and read directly from main memory. It guarantees visibility of variable updates across multiple threads without locking, preventing thread caching issues."
                    },
                    {
                        "q": "What is the transient keyword?",
                        "a": "<h4>transient Keyword</h4>"
                            "Indicates that a field should not be serialized when saving object state. During deserialization, the transient field is initialized to its default value (e.g. <code>null</code> or <code>0</code>)."
                    },
                    {
                        "q": "What are the four access modifiers and their scope?",
                        "a": "<h4>Access Modifiers</h4>"
                            "<table>"
                            "<tr><th>Modifier</th><th>Class</th><th>Package</th><th>Subclass</th><th>Global</th></tr>"
                            "<tr><td><strong>private</strong></td><td>Yes</td><td>No</td><td>No</td><td>No</td></tr>"
                            "<tr><td><strong>default (no keyword)</strong></td><td>Yes</td><td>Yes</td><td>No</td><td>No</td></tr>"
                            "<tr><td><strong>protected</strong></td><td>Yes</td><td>Yes</td><td>Yes</td><td>No</td></tr>"
                            "<tr><td><strong>public</strong></td><td>Yes</td><td>Yes</td><td>Yes</td><td>Yes</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is the instanceof operator?",
                        "a": "<h4>instanceof Operator</h4>"
                            "A binary operator used to test if an object is an instance of a specific class, subclass, or interface at runtime.<br/>"
                            "<pre>if (obj instanceof Dog) {\n  Dog d = (Dog) obj;\n}</pre>"
                    }
                ]
            },
            {
                "head": "Exception Handling",
                "qs": [
                    {
                        "q": "What is the difference between checked and unchecked exceptions?",
                        "a": "<h4>Checked vs. Unchecked Exceptions</h4>"
                            "<ul>"
                            "<li><strong>Checked Exceptions:</strong> Subclasses of <code>Exception</code> (excluding <code>RuntimeException</code>). Checked at compile-time. Code MUST declare or catch them. Examples: <code>IOException</code>, <code>SQLException</code>.</li>"
                            "<li><strong>Unchecked Exceptions:</strong> Subclasses of <code>RuntimeException</code>. Checked at runtime. Do not require compile-time handling. Examples: <code>NullPointerException</code>, <code>ArithmeticException</code>.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between throw and throws?",
                        "a": "<h4>throw vs. throws</h4>"
                            "<ul>"
                            "<li><strong><code>throw</code>:</strong> Used to explicitly trigger an exception instance inside a method. Syntax: <code>throw new Exception(\"Error\");</code></li>"
                            "<li><strong><code>throws</code>:</strong> Used in method signatures to declare that this method might propagate certain exceptions. Syntax: <code>void test() throws IOException {}</code></li>"
                            "</ul>"
                    },
                    {
                        "q": "What is try-with-resources? When should you use it?",
                        "a": "<h4>try-with-resources (Java 7+)</h4>"
                            "A try block that declares one or more resources (objects implementing <code>AutoCloseable</code> or <code>Closeable</code>). These resources are automatically closed in reverse order of initialization when the try block exits.<br/>"
                            "<pre>try (BufferedReader br = new BufferedReader(new FileReader(\"test.txt\"))) {\n  System.out.println(br.readLine());\n}</pre>"
                    },
                    {
                        "q": "Can we have a try block without a catch block?",
                        "a": "<h4>try without catch</h4>"
                            "<strong>Yes</strong>, a try block can be compiled without a catch block as long as it has a <code>finally</code> block, or is declared as a <code>try-with-resources</code> statement."
                    },
                    {
                        "q": "What is custom exception? How do you create one?",
                        "a": "<h4>Custom Exceptions</h4>"
                            "A user-defined exception class to model specific application errors.<br/>"
                            "<ul>"
                            "<li><strong>Checked exception:</strong> Extend <code>java.lang.Exception</code>.</li>"
                            "<li><strong>Unchecked exception:</strong> Extend <code>java.lang.RuntimeException</code>.</li>"
                            "</ul>"
                            "<pre>class InvalidAgeException extends RuntimeException {\n  public InvalidAgeException(String msg) { super(msg); }\n}</pre>"
                    },
                    {
                        "q": "What is the exception hierarchy in Java?",
                        "a": "<h4>Exception Hierarchy</h4>"
                            "<pre>\n          Throwable\n         /         \\\n      Error      Exception\n                /         \\\n     IOException   RuntimeException\n</pre>"
                            "<ul>"
                            "<li><strong>Throwable:</strong> Root class of all exceptions and errors.</li>"
                            "<li><strong>Error:</strong> Critical system errors (e.g. <code>OutOfMemoryError</code>, <code>StackOverflowError</code>). Applications should not attempt to catch.</li>"
                            "<li><strong>Exception:</strong> Application-level conditions that programs should catch.</li>"
                            "</ul>"
                    }
                ]
            },
            {
                "head": "Collections",
                "qs": [
                    {
                        "q": "What is the difference between ArrayList and LinkedList?",
                        "a": "<h4>ArrayList vs. LinkedList</h4>"
                            "<table>"
                            "<tr><th>ArrayList</th><th>LinkedList</th></tr>"
                            "<tr><td>Backed by dynamic arrays.</td><td>Backed by doubly linked nodes.</td></tr>"
                            "<tr><td>Random access <code>O(1)</code>.</td><td>Sequential access <code>O(n)</code>.</td></tr>"
                            "<tr><td>Slower inserts/deletes (array shifts).</td><td>Fast inserts/deletes (pointer changes).</td></tr>"
                            "<tr><td>Less memory per element.</td><td>More memory (stores node links).</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "How does HashMap work internally? What is hashing?",
                        "a": "<h4>HashMap Internals</h4>"
                            "Uses an array of Node buckets (Node class contains: <code>int hash</code>, <code>K key</code>, <code>V value</code>, <code>Node next</code>).<br/>"
                            "<h4>Key Actions:</h4>"
                            "1. <strong>put():</strong> Computes key hash code using <code>hashCode()</code>. Determines bucket index via index formula: <code>index = hash & (n - 1)</code>.<br/>"
                            "2. <strong>Collision:</strong> If multiple keys land in the same bucket, elements are chained in a LinkedList. In Java 8+, if list exceeds threshold (TREEIFY_THRESHOLD = 8), it turns into a Balanced Tree (Red-Black Tree) to improve lookup from <code>O(n)</code> to <code>O(log n)</code>."
                    },
                    {
                        "q": "What is the difference between HashMap and Hashtable?",
                        "a": "<h4>HashMap vs. Hashtable</h4>"
                            "<table>"
                            "<tr><th>HashMap</th><th>Hashtable</th></tr>"
                            "<tr><td>Non-synchronized (not thread-safe).</td><td>Synchronized (thread-safe, slower).</td></tr>"
                            "<tr><td>Allows one null key, multiple null values.</td><td>Does not allow null keys or values.</td></tr>"
                            "<tr><td>Fast performance.</td><td>Legacy class, slow.</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is the difference between HashSet, LinkedHashSet, and TreeSet?",
                        "a": "<h4>Set Comparisons</h4>"
                            "<ul>"
                            "<li><strong>HashSet:</strong> Backed by HashMap. Unordered. Fast <code>O(1)</code> operations.</li>"
                            "<li><strong>LinkedHashSet:</strong> Maintains insertion order using a doubly-linked list.</li>"
                            "<li><strong>TreeSet:</strong> Backed by Red-Black Tree. Elements sorted naturally or by Comparator. <code>O(log n)</code> operations.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between Iterator and ListIterator?",
                        "a": "<h4>Iterator vs. ListIterator</h4>"
                            "<ul>"
                            "<li><strong>Iterator:</strong> Traverse map or lists in forward direction only. Can delete elements.</li>"
                            "<li><strong>ListIterator:</strong> Only for <code>List</code>. Can traverse in both directions (forward/backward) and modify list (add/set elements).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is a fail-fast iterator vs fail-safe iterator?",
                        "a": "<h4>Fail-Fast vs. Fail-Safe Iterators</h4>"
                            "<ul>"
                            "<li><strong>Fail-Fast:</strong> Works on original collection. Throws <code>ConcurrentModificationException</code> if collection is modified structurally during iteration (using modCount). Examples: ArrayList, HashMap iterators.</li>"
                            "<li><strong>Fail-Safe (Weakly Consistent):</strong> Works on a copy of the collection. Does not throw exceptions if modified during iteration. Examples: CopyOnWriteArrayList, ConcurrentHashMap.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is Comparable vs Comparator?",
                        "a": "<h4>Comparable vs. Comparator</h4>"
                            "<ul>"
                            "<li><strong>Comparable:</strong> Interface implementing <code>compareTo(obj)</code> to define natural sorting of the class. Modifies target class directly.</li>"
                            "<li><strong>Comparator:</strong> Separate helper class implementing <code>compare(obj1, obj2)</code> to define custom sorting rules. Does not modify original class.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between poll() and remove() in Queue?",
                        "a": "<h4>Queue Method Comparison</h4>"
                            "Both retrieve and remove the head element of the queue.<br/>"
                            "<ul>"
                            "<li><strong><code>poll()</code>:</strong> Returns <code>null</code> if the queue is empty.</li>"
                            "<li><strong><code>remove()</code>:</strong> Throws <code>NoSuchElementException</code> if the queue is empty.</li>"
                            "</ul>"
                    },
                    {
                        "q": "When would you use a PriorityQueue?",
                        "a": "<h4>PriorityQueue</h4>"
                            "Used when elements must be processed based on their natural priority or custom ordering rather than standard FIFO.<br/>"
                            "<em>Example:</em> Job scheduling systems where high priority tasks run first."
                    }
                ]
            },
            {
                "head": "Generics",
                "qs": [
                    {
                        "q": "What are generics and why are they used?",
                        "a": "<h4>Generics</h4>"
                            "Introduced in Java 5 to enable type-safe programming.<br/>"
                            "<h4>Benefits:</h4>"
                            "<ul>"
                            "<li>Type safety (enforces correct data types at compile time).</li>"
                            "<li>Eliminates runtime typecasting and class cast exceptions.</li>"
                            "<li>Allows writing generic algorithms that apply to multiple types.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is type erasure in generics?",
                        "a": "<h4>Type Erasure</h4>"
                            "The process by which the Java compiler strips generic type parameters at compile-time and replaces them with their bounds (or <code>Object</code>) to maintain backwards compatibility with older, raw non-generic code. No generic info exists at JVM runtime."
                    },
                    {
                        "q": "What is the difference between List<?>, List<Object>, and List<T>?",
                        "a": "<h4>List Type Differences</h4>"
                            "<ul>"
                            "<li><strong><code>List<?></code>:</strong> List of unknown type (Wildcard). Read-only; you cannot add elements to it (except null) because compiler cannot guarantee the list type.</li>"
                            "<li><strong><code>List<Object></code>:</strong> List of Object class instances. You can write any object to it, but you cannot assign it to generic types like <code>List<String></code> due to invariance.</li>"
                            "<li><strong><code>List<T></code>:</strong> Generic list parameter placeholder inside generic classes or methods.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is an upper-bounded wildcard (extends) vs lower-bounded wildcard (super)?",
                        "a": "<h4>Upper bounds vs. Lower bounds</h4>"
                            "<ul>"
                            "<li><strong>Upper-Bounded (<code>? extends T</code>):</strong> Restricts elements to type T and subclasses. Read operations are safe; write operations are restricted (useful for producers).</li>"
                            "<li><strong>Lower-Bounded (<code>? super T</code>):</strong> Restricts elements to type T and superclasses. Safe to write elements of type T; read operations yield only type <code>Object</code> (useful for consumers).</li>"
                            "</ul>"
                    }
                ]
            },
            {
                "head": "Java 8+ Features",
                "qs": [
                    {
                        "q": "What is a functional interface? Give examples from java.util.function.",
                        "a": "<h4>Functional Interface</h4>"
                            "An interface containing exactly one abstract method (annotated with <code>@FunctionalInterface</code>). Can contain multiple default or static methods.<br/>"
                            "<h4>Examples from java.util.function:</h4>"
                            "<ul>"
                            "<li><code>Predicate<T></code>: Takes T, returns boolean (<code>test(T t)</code>).</li>"
                            "<li><code>Function<T,R></code>: Takes T, returns R (<code>apply(T t)</code>).</li>"
                            "<li><code>Consumer<T></code>: Takes T, returns void (<code>accept(T t)</code>).</li>"
                            "<li><code>Supplier<T></code>: Takes nothing, returns T (<code>get()</code>).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What are lambda expressions? Write an example.",
                        "a": "<h4>Lambda Expressions</h4>"
                            "An anonymous block of code (function) used to implement a functional interface in a concise way.<br/>"
                            "<pre>// Traditional anonymous class:\nRunnable r1 = new Runnable() {\n  public void run() { System.out.println(\"Hi\"); }\n};\n"
                            "// Lambda expression:\nRunnable r2 = () -> System.out.println(\"Hi\");"
                            "</pre>"
                    },
                    {
                        "q": "What are the common Stream API operations (map, filter, reduce, collect)?",
                        "a": "<h4>Stream Operations</h4>"
                            "<ul>"
                            "<li><strong><code>filter()</code>:</strong> Intermediate operation. Selects elements matching a predicate.</li>"
                            "<li><strong><code>map()</code>:</strong> Intermediate operation. Transforms each element using a function.</li>"
                            "<li><strong><code>reduce()</code>:</strong> Terminal operation. Aggregates stream elements into a single value.</li>"
                            "<li><strong><code>collect()</code>:</strong> Terminal operation. Converts streams to lists, sets, etc.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between map() and flatMap()?",
                        "a": "<h4>map() vs. flatMap()</h4>"
                            "<ul>"
                            "<li><strong><code>map()</code>:</strong> One-to-one transformation. Transforms elements but keeps the structural nested nesting (e.g. stream of lists remains a stream of lists).</li>"
                            "<li><strong><code>flatMap()</code>:</strong> One-to-many transformation. Flattens nested collections (e.g. flattens <code>Stream&lt;List&lt;String&gt;&gt;</code> into a unified <code>Stream&lt;String&gt;</code>).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the Optional class and how does it prevent NullPointerException?",
                        "a": "<h4>Optional Class (Java 8)</h4>"
                            "A container wrapper object which may or may not contain a non-null value. It helps design clean APIs that avoid returning <code>null</code>.<br/>"
                            "<pre>Optional<String> name = Optional.ofNullable(getName());\n"
                            "String result = name.orElse(\"Default Name\"); // avoids NPE</pre>"
                    },
                    {
                        "q": "What are method references? What are the four types?",
                        "a": "<h4>Method References</h4>"
                            "Shorthand syntax for lambdas that call existing methods. Syntax uses <code>::</code>.<br/>"
                            "<h4>Four Types:</h4>"
                            "1. Static method reference: <code>Math::max</code><br/>"
                            "2. Instance method reference on specific object: <code>System.out::println</code><br/>"
                            "3. Instance method reference of arbitrary object type: <code>String::toUpperCase</code><br/>"
                            "4. Constructor reference: <code>ArrayList::new</code>"
                    },
                    {
                        "q": "What is the difference between intermediate and terminal stream operations?",
                        "a": "<h4>Intermediate vs. Terminal Operations</h4>"
                            "<ul>"
                            "<li><strong>Intermediate:</strong> Returns another Stream. Lazily evaluated (doesn't run until terminal operation runs). Examples: <code>filter()</code>, <code>map()</code>.</li>"
                            "<li><strong>Terminal:</strong> Performs aggregation or side-effects and returns a non-stream type. Triggers execution of the stream pipeline. Examples: <code>collect()</code>, <code>forEach()</code>, <code>count()</code>.</li>"
                            "</ul>"
                    }
                ]
            },
            {
                "head": "Multithreading",
                "qs": [
                    {
                        "q": "What is the difference between Thread and Runnable?",
                        "a": "<h4>Thread vs. Runnable</h4>"
                            "<ul>"
                            "<li><strong>Thread:</strong> Class representing a thread of execution. You must subclass it and override <code>run()</code>. Cons: limits class inheritance.</li>"
                            "<li><strong>Runnable:</strong> Interface defining <code>run()</code> method. Better practice as you can implement it while extending other parent classes.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What are the thread states in Java?",
                        "a": "<h4>Thread Lifecycle States</h4>"
                            "1. <strong>NEW:</strong> Created but not yet started (before <code>start()</code>).<br/>"
                            "2. <strong>RUNNABLE:</strong> Ready to execute (waiting in thread pool scheduler queue).<br/>"
                            "3. <strong>BLOCKED:</strong> Waiting to acquire a monitor lock.<br/>"
                            "4. <strong>WAITING:</strong> Waiting indefinitely for notification (e.g. via <code>wait()</code>).<br/>"
                            "5. <strong>TIMED_WAITING:</strong> Waiting for specified duration (e.g. <code>sleep(ms)</code>).<br/>"
                            "6. <strong>TERMINATED:</strong> Finished executing run code."
                    },
                    {
                        "q": "What is synchronization? What problem does it solve?",
                        "a": "<h4>Synchronization</h4>"
                            "Controlling multi-thread access to a shared resource. Prevents <strong>race conditions</strong> where concurrent writes corrupt data state."
                    },
                    {
                        "q": "What is the difference between synchronized method and synchronized block?",
                        "a": "<h4>Synchronized Method vs. Block</h4>"
                            "<ul>"
                            "<li><strong>Synchronized Method:</strong> Locks the entire method. Synchronizes on the current instance (<code>this</code>) or class object.</li>"
                            "<li><strong>Synchronized Block:</strong> Locks only specified statements. Allows choosing target lock object, maximizing performance by narrowing block scope.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between wait() and sleep()?",
                        "a": "<h4>wait() vs. sleep()</h4>"
                            "<table>"
                            "<tr><th>Feature</th><th>wait()</th><th>sleep()</th></tr>"
                            "<tr><td><strong>Class</strong></td><td>Object class</td><td>Thread class</td></tr>"
                            "<tr><td><strong>Locks</strong></td><td>Releases monitor lock</td><td>Retains lock ownership</td></tr>"
                            "<tr><td><strong>Wake up</strong></td><td>Needs <code>notify()</code>/<code>notifyAll()</code></td><td>Awakens automatically after timeout</td></tr>"
                            "</table>"
                    },
                    {
                        "q": "What is a deadlock? How can you prevent it?",
                        "a": "<h4>Deadlock</h4>"
                            "A scenario where thread A holds lock 1 and waits for lock 2, while thread B holds lock 2 and waits for lock 1. Both wait forever.<br/>"
                            "<h4>Prevention:</h4>"
                            "<ul>"
                            "<li>Acquire locks in consistent global order.</li>"
                            "<li>Avoid locking nested resources.</li>"
                            "<li>Use timeouts (like <code>ReentrantLock.tryLock()</code>).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is the difference between Runnable and Callable?",
                        "a": "<h4>Runnable vs. Callable</h4>"
                            "<ul>"
                            "<li><strong>Runnable:</strong> Cannot return method results. Cannot throw checked exceptions (uses <code>run()</code>).</li>"
                            "<li><strong>Callable (Java 5):</strong> Returns a generic result value. Can throw checked exceptions (uses <code>call()</code>).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is a thread pool (ExecutorService)?",
                        "a": "<h4>Thread Pools</h4>"
                            "A managed cache pool of reusable worker threads. Avoids resource overhead of creating/destroying threads constantly.<br/>"
                            "Created using <code>Executors</code> factory methods (e.g. <code>newFixedThreadPool(n)</code>)."
                    }
                ]
            },
            {
                "head": "Misc",
                "qs": [
                    {
                        "q": "What is serialization and deserialization? What is serialVersionUID?",
                        "a": "<h4>Serialization</h4>"
                            "Converting an object state into a byte stream to write to files/databases or transmit over network. <strong>Deserialization</strong> is restoring object state from that byte stream.<br/>"
                            "<h4>serialVersionUID:</h4>"
                            "A unique version identifier associated with serialized data to verify that the sender and receiver classes have matching compatible versions."
                    },
                    {
                        "q": "What is shallow copy vs deep copy?",
                        "a": "<h4>Shallow vs. Deep Copy</h4>"
                            "<ul>"
                            "<li><strong>Shallow Copy:</strong> Copies the top-level object fields. References inside are shared between copy and original object.</li>"
                            "<li><strong>Deep Copy:</strong> Recursively copies all objects referenced, resulting in completely independent objects.</li>"
                            "</ul>"
                    },
                    {
                        "q": "What is autoboxing and unboxing?",
                        "a": "<h4>Autoboxing & Unboxing</h4>"
                            "<ul>"
                            "<li><strong>Autoboxing:</strong> Compiler automatically converting primitive types to corresponding wrapper classes (e.g., <code>int</code> to <code>Integer</code>).</li>"
                            "<li><strong>Unboxing:</strong> Converting wrapper object to primitive (e.g., <code>Integer</code> to <code>int</code>).</li>"
                            "</ul>"
                    },
                    {
                        "q": "What are varargs? Give an example.",
                        "a": "<h4>Varargs (Variable Arguments)</h4>"
                            "Enables a method to accept zero or more arguments of a specified type using <code>...</code> syntax.<br/>"
                            "<pre>void printAll(String... names) {\n  for(String s : names) System.out.println(s);\n}</pre>"
                    },
                    {
                        "q": "What is an enum? Can an enum have a constructor and methods?",
                        "a": "<h4>Enum</h4>"
                            "A special class type defining a fixed set of constants.<br/>"
                            "<strong>Yes</strong>, enums can contain instance fields, constructors (implicitly private), and methods."
                    }
                ]
            }
        ]
    }
    
    # Check if exists, replace or append
    idx = -1
    for i, m in enumerate(db):
        if m['id'] == 0:
            idx = i
            break
    if idx != -1:
        db[idx] = core_java
    else:
        db.append(core_java)
        
    save_db(db)
    print("Core Java data populated successfully.")

if __name__ == '__main__':
    main()
